version: '3.8'

services:
  web:
    build:
      context: ./my-next-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/jardins_cocagne
    depends_on:
      - db
    volumes:
      - ./my-next-app:/app
      - /app/node_modules

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: jardins_cocagne
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./my-next-app/lib/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: