name: Docker Build and Test

on:
  push:
    paths:
      - 'docker-compose.yml'
      - '**/Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        docker-compose -f docker-compose.yml up -d --build
        docker-compose exec web npm run lint
        docker-compose exec web npm run test:unit
        docker-compose exec web npm run test:e2e

    - name: Tear down Docker containers
      run: docker-compose down