name: CD

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        docker-compose -f docker-compose.yml up -d --build
        docker-compose exec web npm run lint
        docker-compose exec web npm run test:unit
        docker-compose exec web npm run test:e2e

    - name: Deploy to Vercel
      run: npx vercel deploy --prod
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    - name: Tear down Docker containers
      run: docker-compose down